### ISSUE TITLE
Panic when trying to spawn text as a child of a node bundle

### ISSUE THREAD

**Issue by wandbrandon** [Seldom-SE/seldom_pixel#6]
Hi, while attempting to incorporate bitmap fonts into my code I came across this plugin. Unfortunately, creating a pixel perfect UI in bevy is a hassle, right now I'm simply trying to add the PxTextBundle as a child to NodeBundle. Here's the code:

```rust
use bevy::prelude::*;
use seldom_pixel::prelude::*;

use crate::ui::{
    menu_handler::MenuHandlerPlugin, seldom_ui::SeldomUiPlugin,
    ui_pixel_perfect::UiPixelPerfectPlugin,
};

use self::{common::InGameCamera, seldom_ui::Layer};

mod bounty;
mod common;
mod inventory;
mod menu_handler;
mod seldom_ui;
mod ui_pixel_perfect;

#[derive(Component)]
///Struct for main menu component
pub struct MainMenuComponent;

/// Struct to define the UI plugin
pub struct UiPlugin;

impl Plugin for UiPlugin {
    fn build(&self, app: &mut App) {
        info!("Building UI plugin...");
        app.add_systems(Startup, init_ui);
        app.add_plugins(SeldomUiPlugin);
        //app.add_plugins(MenuHandlerPlugin);
    }
}

fn init_ui(
    mut commands: Commands,
    query: Query<Entity, With<InGameCamera>>,
    mut typefaces: PxAssets<PxTypeface>,
) {
    let camera_entity = query.get_single().expect("No InGameCamera");

    commands
        .spawn((
            NodeBundle {
                style: Style {
                    flex_direction: FlexDirection::Column,
                    justify_content: JustifyContent::SpaceBetween,
                    align_items: AlignItems::Stretch,
                    width: Val::Percent(100.),
                    height: Val::Percent(100.),
                    padding: UiRect {
                        left: Val::Px(10.),
                        right: Val::Px(10.),
                        top: Val::Px(10.),
                        bottom: Val::Px(10.),
                    },
                    ..Default::default()
                },
                background_color: Color::BISQUE.into(),
                ..Default::default()
            },
            MainMenuComponent,
            TargetCamera(camera_entity),
        ))
        .with_children(|builder| {
            builder.spawn(PxTextBundle::<Layer> {
                text: "Testing".into(),
                typeface: typefaces.load(
                    "typefaces/3x5spaceremoved.png",
                    &"!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~".chars().rev().collect::<String>(),
                    [(' ', 3)]),
                rect: IRect::new(0, 0, 64, 64).into(),
                ..default()
            });
        });
}
```

The SeldomUI Plugin i made 
```rust
use bevy::prelude::*;
use seldom_pixel::prelude::*;

use super::common::InGameCamera;

pub struct SeldomUiPlugin;

impl Plugin for SeldomUiPlugin {
    fn build(&self, app: &mut App) {
        info!("Building Seldom UI plugin...");
        app.add_plugins(PxPlugin::<Layer>::new(
            UVec2::new(480, 270),
            "palettes/palette_1.png".into(),
        ));
        app.insert_resource(ClearColor(Color::BLACK));
        app.add_systems(PreStartup, init);
    }
}

fn init(mut commands: Commands) {
    commands.spawn((Camera2dBundle::default(), InGameCamera));
}

#[px_layer]
pub struct Layer;
```

Here's the panic:
```
thread '<unnamed>' panicked at dreambound_lib/src/ui/mod.rs:39:44:
No InGameCamera: NoEntities("bevy_ecs::query::state::QueryState<bevy_ecs::entity::Entity, bevy_ecs::query::filter::With<dreambound_lib::ui::common::InGameCamera>>")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `dreambound_lib::ui::init_ui`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
thread 'main' panicked at /Users/brandonwand/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by Seldom-SE** [comment]
The panic is on `let camera_entity = query.get_single().expect("No InGameCamera");`, so it doesn't seem related to the UI. Make sure `SeldomUiPlugin` is being added.

That said, Bevy's UI and `PxTextBundle` are incompatible. If you want a background for your text, you can spawn a sprite (as an unrelated entity. `seldom_pixel` doesn't use children) with the color you want. I think text draws over sprites by default, so you don't have to mess with layers.
